version: '3'
services:
  app:
    build: .
    container_name: app
    depends_on:
      - db
    ports:
      - 8888:7777

  db:
    image: 'postgres:13'
    container_name: db
    ports:
    - 5444:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=springdb
    volumes:
      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql